# Generated by Django 4.2.11 on 2026-05-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('latitude_min', models.FloatField()),
                ('latitude_max', models.FloatField()),
                ('longitude_min', models.FloatField()),
                ('longitude_max', models.FloatField()),
                ('coverage_percentage_3g', models.FloatField(default=0)),
                ('coverage_percentage_4g', models.FloatField(default=0)),
                ('coverage_percentage_5g', models.FloatField(default=0)),
                ('avg_signal_strength_3g', models.FloatField(blank=True, null=True)),
                ('avg_signal_strength_4g', models.FloatField(blank=True, null=True)),
                ('avg_signal_strength_5g', models.FloatField(blank=True, null=True)),
                ('total_towers', models.IntegerField(default=0)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dominant_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.networkprovider')),
            ],
            options={
                'verbose_name_plural': 'Coverage Analysis',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='NetworkComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('avg_signal_provider1', models.FloatField()),
                ('avg_signal_provider2', models.FloatField()),
                ('coverage_area_provider1', models.FloatField(help_text='Coverage area in sq km')),
                ('coverage_area_provider2', models.FloatField(help_text='Coverage area in sq km')),
                ('reliability_score_provider1', models.FloatField()),
                ('reliability_score_provider2', models.FloatField()),
                ('comparison_date', models.DateTimeField(auto_now_add=True)),
                ('provider1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_provider1', to='networks.networkprovider')),
                ('provider2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_provider2', to='networks.networkprovider')),
            ],
            options={
                'ordering': ['-comparison_date'],
                'unique_together': {('provider1', 'provider2', 'region_name')},
            },
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('measurements_count', models.IntegerField(default=0)),
                ('avg_signal_strength', models.FloatField()),
                ('max_signal_strength', models.IntegerField()),
                ('min_signal_strength', models.IntegerField()),
                ('uptime_percentage', models.FloatField(default=100)),
                ('user_satisfaction', models.FloatField(default=0, help_text='0-100 scale')),
                ('network_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.networktype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='networks.networkprovider')),
            ],
            options={
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
                'unique_together': {('date', 'provider', 'network_type')},
            },
        ),
    ]
