# Generated by Django 4.2.11 on 2026-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageanalysis',
            name='avg_signal_strength_2g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverageanalysis',
            name='congestion_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='coverageanalysis',
            name='congestion_score',
            field=models.FloatField(default=0, help_text='0-100 congestion score'),
        ),
        migrations.AddField(
            model_name='coverageanalysis',
            name='coverage_percentage_2g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='signal_variance',
            field=models.FloatField(default=0, help_text='Signal stability (lower = more stable)'),
        ),
    ]
