# Generated by Django 4.2.11 on 2026-05-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provider_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Network Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('3G', '3G'), ('4G', '4G LTE'), ('5G', '5G')], max_length=10, unique=True)),
                ('description', models.TextField()),
                ('frequency_band', models.CharField(max_length=100)),
                ('max_speed', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='AvailableNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_strength', models.IntegerField(help_text='Signal strength in dBm')),
                ('signal_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('no_signal', 'No Signal')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('network_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_networks', to='networks.networktype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_networks', to='networks.networkprovider')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='networks_av_latitud_41272c_idx'), models.Index(fields=['provider', 'network_type'], name='networks_av_provide_5ea61d_idx')],
            },
        ),
    ]
