# Generated by Django 4.2.11 on 2026-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktype',
            name='type',
            field=models.CharField(choices=[('2G', '2G GSM'), ('EDGE', 'EDGE'), ('3G', '3G'), ('4G', '4G LTE'), ('5G', '5G')], max_length=10, unique=True),
        ),
    ]
